opendkim: /opt/opendkim.sh
postfix: /opt/postfix.sh
tachikoma_utils: bash -c "while ! nc -z localhost 25; do sleep 0.1; done; su tachikoma -c '/opt/tachikoma-postfix-utils/bin/tachikoma-postfix-utils $TACHIKOMA_CONFIG'"
syslog: bash -c "while ! nc -z localhost 25; do sleep 0.1; done; /usr/sbin/rsyslogd -n"